### ISSUE TITLE
Build failure with 0.10.0.1

### ISSUE THREAD

**Issue by DanBurton** [alcidesv/second-transfer#4]
I'm seeing this error on Stackage nightly. Is this just a c library we need to make available on the build server?

```
[48 of 48] Compiling SecondTransfer   ( hs-src/SecondTransfer.hs, dist/build/SecondTransfer.o )

cbits/enable_tls.cpp:9:25:
     fatal error: botan/botan.h: No such file or directory
     #include <botan/botan.h>
                             ^
```

**Comment by alcidesv** [comment]
Thank you Dan. Yes, it's a dependency against libbotan. The library is  fundamental for the  project, but the the project can be built without the library and the tests will run fine. I've uploaded version 0.10.0.2 of the package where use of libbotan is disabled by default.
